config/routes.rb
MusicFeedApp::Application.routes.draw do
  get "admin/index"
  get '/admin/hoursWorked'
  root 'sessions#new'
  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  resources :work_orders
  resources :attachments
  resources :ull_team_members
  resources :password_resets

  scope "/admin" do
    resources :projects do
      collection do
        get 'assign'
      end
    end
  end
    
  scope "/admin" do
    resources :project_datas do
      collection do
        get 'assign'
      end
    end
  end
     
  resources :project_datas do
    member do
       get 'project_managers'
    end
  end

  get 'login', to: 'welcome#index'
  get '/help', to: 'welcome#help'
  get 'welcome/index', to: 'welcome#index'
  get '/load_today_data', to: 'time_sheets#loadToDay'
  post '/saveTimeSheets', to: 'time_sheets#saveTime'
  post '/saveDayTimesheets', to: 'time_sheets#saveDayTime'
  get 'welcome/weekFunc', to: 'time_sheets#weekFunc'
  get '/createPieChart', to: 'time_sheets#createPieChart'
  get '/checkPrevTimeSheets', to: 'time_sheets#checkPrevTimeSheets'
  match '/deleteDayTimesheets', :to => 'time_sheets#deleteDayTimesheets', via: [:get, :post]
  get '/UserGuide', :to => 'time_sheets#user_guide'
  get '/ProjectsPersonnel', :to => 'projects#project_page'

  match '/auth/:provider/callback' => 'sessions#create' , via: [:get, :post]
  match "/auth/failure" => "sessions#failure", via: [:get, :post]
  get '/signin',  to: 'sessions#new'
  get '/signout', to: 'sessions#destroy'
  get '/signup', to: 'users#new'
  get '/Client', to: 'sessions#new_client'
  get '/renderRoleInfo', to: 'sessions#render_role_info'

  get '/monthlyClassifiedReport', to: 'admin#monthlyEmployeeReport'
  get '/registration', to: 'registrations#new'
  get '/view_report', to: 'time_sheets#view_report'
  get '/send_mail', to: 'time_sheets#send_mail'
  get '/activate_user', to: "time_sheets#activate_user"
  get '/time_sheet_reports', to: "time_sheets#time_sheet_reports"

    get "/project_colors", to: 'report#project_colors'
    get '/createReportPieChart', to: 'report#createReportPieChart'
    get '/createCustomReport', to: 'report#createCustomReport'
    get '/TimeSummaries', to: 'time_sheets#report'
    get '/projectReport', to: 'report#projectReport'
    get '/sendReportReminder', to: 'report#reminder'
  
    get '/send_report', to: "time_sheets#send_report"
    get '/submit_report', to: 'time_sheets#submit_report'
    get '/weeklyTimeView', to: 'time_sheets#weekly_time_view'
    get '/checkPrevWeekHours', to: 'time_sheets#check_prev_week_hours'

    get 'work_orders/index', to: 'work_orders#index'
    get '/work_order_admin', to: 'work_order_admin#index'
    get'/processReport', to: 'work_order_admin#process_report'
    get '/work_order_assignment/:id', to: 'work_order_admin#assignment'
    get '/work_order_review/:id', to: 'work_order_admin#review'
	  get '/work_order_submit', to: 'work_orders#submit'
	  get '/work_order_approve', to: 'work_order_admin#approve'
	  get '/deleteAttachment', to: 'work_orders#delete_attachment'
	  get '/buildAttachment', to: 'work_orders#build_attachment'
	  get '/WorkOrderTracking', to: 'work_order_admin#work_order_tracking'
	  get '/getAttachments', to: 'work_orders#get_attachments'
	  get '/clearAllAttachments', to: 'work_orders#clear_all_attachments'	
	  get '/checkAttachment', to: 'work_orders#check_attachment'
	  post '/dropzone', to: 'work_orders#dropzone'
	  get '/getWOData', to: 'work_order_admin#get_WO_data'
	  get '/getEmails', to: 'work_order_admin#get_emails'
	  get '/saveAWOEdits', to: 'work_order_admin#save_awo_edits'
	  get '/getOfficePercents', to: 'work_order_admin#get_office_percents'
    get "/monthly_quarterly_CSV", to: "work_order_admin#monthly_quarterly_CSV"
    get "/yearlyCSV", to: "work_order_admin#yearlyCSV"
    get "/weeklyCSV", to: "work_order_admin#weeklyCSV"
		get "/get_admin_data", to: "work_order_admin#get_admin_data"
		
		

  get "/admin", to: 'admin#index'
  get "/admin/users", to: 'admin#users'
  post "/updateUser", to: 'admin#updateUser'
  get "/reportingusers", to: "admin#assign_users"
  post "/activateProject", to: "projects#activate"
  post "/deactivateProject", to: "projects#deactivate"
  get "/archived_projects", to: "projects#archived"
  get "/archivedProjectdetails", to: "projects#archivedProjectDetails"
  get '/saveProject', to: 'projects#save_project'
  get '/archiveProject', to: 'projects#archive_project'
  get '/createProject', to: 'projects#create_project'
  get '/editUserPermissions', to: 'admin#edit_permissions'
  get '/usersTable', to: 'admin#users_table'
  get '/get_user_permissions', to: 'admin#get_user_permissions' 
  get '/delete_role', to: 'admin#delete_role'
  get '/edit_custom_role', to: 'admin#edit_custom_role'
  get '/save_new_role', to: 'admin#save_new_role'
  get '/get_custom_role_permissions', to: 'admin#get_custom_role_permissions'
  get '/load_custom_roles', to: 'admin#load_custom_roles'
  get '/get_role_hierarchy', to: 'admin#get_role_hierarchy'
  get '/load_new_role', to: 'admin#load_new_role'
  get '/load_user_info', to: 'admin#load_user_info'
  get '/disable_user', to: 'admin#disable_user'
  get '/enable_user', to: 'admin#enable_user'
  get "/delete_user", to: 'admin#delete_user'
  get '/users_table', to: 'admin#users_table'
  get'/reload_assigned_users', to: 'projects#reload_assigned_users'

  
  get "/manager", to: "manager#manager"
  post "/assignProjects", to: "manager#assignProjects"
  post "/removeProjects", to: "manager#removeProjects"
  get '/searchUsers', :to => 'manager#searchUsers'
  get '/getUsersList', :to => 'manager#getUsersList'
  
  get '/verify_report', to: 'time_sheets#verify_report'
  get '/approve_report', to: 'time_sheets#approve_report'
  get '/reject_report', to: 'time_sheets#reject_report'
  get "/manageReports", to: "admin#manageReports"
  get "/tsmanageReports", to: "admin#manageReports"
  get "/ts_manager_csvReport", to: "admin#ts_manager_csvReport"
  get '/renderUserData', to: 'admin#render_user_data'
  
  
  get '/saveModifiedHours', to: "admin#saveModifiedHours"
  post '/saveModifiedHours', to: "admin#saveModifiedHours"
  get '/newReport', to: "admin#newReportEmployee"
  get '/employeeReportUpdated', to: "admin#employeeReportUpdated"
  get '/update_user_lock', to: 'admin#update_user_lock'
  get '/update_all_locks', to: 'admin#update_all_locks'
  get '/update_project_locks', to: 'admin#update_project_locks'
  get '/update_all_project_locks', to: 'admin#update_all_project_locks'
  get '/update_prev_month_all_lock', to: 'admin#update_prev_month_all_lock'
  get '/update_prev_month_user_lock', to: 'admin#update_prev_month_user_lock'
  get '/check_TS_locks', to: 'time_sheets#check_TS_locks'
  match 'active'  => 'sessions#active',  via: :get
  match 'timeout' => 'sessions#timeout', via: :get
  
  
  
  get '/versionUpdates', to: 'versions#index'
  
  get '404', to: redirect('/')
  
    

end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_micropost_form.html.erb
<% if signed_in? %>
	<%= form_for(@micropost) do |f| %>
	  <%= f.hidden_field :petition_id, :value => @petition.id %>
		<%= f.text_area :content, placeholder: "Comment here...", class: "span12", rows:"5" %>
		<div class="row">
		<%= f.hidden_field :location, :value => @location %>
		<%= f.submit "Post", class: "btn btn-large btn-primary", id: "right"  %>
		</div>
	<% end %>
<% else %>
		<textarea placeholder="Comment here...", class="span12", rows="5"></textarea> 
		<div class="row">
		<%= link_to "Sign in to comment", signin_path, class: "btn btn-large btn-primary", id: "right" %>
		</div>
<% end %>	

app/views/shared/_text_editor.html.erb
<div id="wysihtml5-toolbar" style="display: none;">
	 <div class="btn-toolbar">
		 <div class="btn-group"> 
			  <a class = "btn" data-wysihtml5-command="bold" title="CTRL+B"><b>bold</b></a>
			  <a class = "btn" data-wysihtml5-command="italic" title="CTRL+I"><i>italic</i></a>
			  <a class = "btn" data-wysihtml5-command="underline" title="CTRL+U"><u>underline</u></a>
		 </div>
		  
		 <div class="btn-group">
			  <a class="btn" data-wysihtml5-command="insertUnorderedList" title="Unordered List" href="javascript:;" unselectable="on"><i class="icon-list"></i></a>
			  <a class="btn" data-wysihtml5-command="insertOrderedList" title="Ordered List" href="javascript:;" unselectable="on"><i class="icon-th-list"></i></a>
			  <a class="btn" data-wysihtml5-command="Indent" title="Indent" href="javascript:;" unselectable="on"><i class="icon-indent-left"></i></a>  
			  <a class="btn" data-wysihtml5-command="Outdent" title="Outdent" href="javascript:;" unselectable="on"><i class="icon-indent-right"></i></a>
		 </div>
		 
		 <div class="btn-group">
				<a class="btn" data-wysihtml5-command="formatBlock" data-wysihtml5-command-value="div" href="javascript:;" unselectable="on">Normal text</a>
				<a class="btn" data-wysihtml5-command="formatBlock" data-wysihtml5-command-value="h1" href="javascript:;" unselectable="on">Heading 1</a>  
				<a class="btn" data-wysihtml5-command="formatBlock" data-wysihtml5-command-value="h2" href="javascript:;" unselectable="on">Heading 2</a>
		 </div>
		</div>  
</div>	

app/views/shared/_text_editor3.html.erb
<div id="wysihtml5-toolbar3" style="display: none;">
	 <div class="btn-toolbar">
		 <div class="btn-group"> 
			  <a class = "btn" data-wysihtml5-command="bold" title="CTRL+B"><b>bold</b></a>
			  <a class = "btn" data-wysihtml5-command="italic" title="CTRL+I"><i>italic</i></a>
			  <a class = "btn" data-wysihtml5-command="underline" title="CTRL+U"><u>underline</u></a>
		 </div>
		  
		 <div class="btn-group">
			  <a class="btn" data-wysihtml5-command="insertUnorderedList" title="Unordered List" href="javascript:;" unselectable="on"><i class="icon-list"></i></a>
			  <a class="btn" data-wysihtml5-command="insertOrderedList" title="Ordered List" href="javascript:;" unselectable="on"><i class="icon-th-list"></i></a>
			  <a class="btn" data-wysihtml5-command="Indent" title="Indent" href="javascript:;" unselectable="on"><i class="icon-indent-left"></i></a>  
			  <a class="btn" data-wysihtml5-command="Outdent" title="Outdent" href="javascript:;" unselectable="on"><i class="icon-indent-right"></i></a>
		 </div>
		 
		 <div class="btn-group">
				<a class="btn" data-wysihtml5-command="formatBlock" data-wysihtml5-command-value="div" href="javascript:;" unselectable="on">Normal text</a>
				<a class="btn" data-wysihtml5-command="formatBlock" data-wysihtml5-command-value="h1" href="javascript:;" unselectable="on">Heading 1</a>  
				<a class="btn" data-wysihtml5-command="formatBlock" data-wysihtml5-command-value="h2" href="javascript:;" unselectable="on">Heading 2</a>
		 </div>
		</div>  
</div>	