config/routes.rb
MusicFeedApp::Application.routes.draw do
  get "admin/index"
  get '/admin/hoursWorked'
  root 'sessions#new'
  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  resources :work_orders
  resources :attachments
  resources :ull_team_members
  resources :password_resets

  scope "/admin" do
    resources :projects do
      collection do
        get 'assign'
      end
    end
  end
    
  scope "/admin" do
    resources :project_datas do
      collection do
        get 'assign'
      end
    end
  end
     
  resources :project_datas do
    member do
       get 'project_managers'
    end
  end

  get 'login', to: 'welcome#index'
  get '/help', to: 'welcome#help'
  get 'welcome/index', to: 'welcome#index'
  get '/load_today_data', to: 'time_sheets#loadToDay'
  post '/saveTimeSheets', to: 'time_sheets#saveTime'
  post '/saveDayTimesheets', to: 'time_sheets#saveDayTime'
  get 'welcome/weekFunc', to: 'time_sheets#weekFunc'
  get '/createPieChart', to: 'time_sheets#createPieChart'
  get '/checkPrevTimeSheets', to: 'time_sheets#checkPrevTimeSheets'
  match '/deleteDayTimesheets', :to => 'time_sheets#deleteDayTimesheets', via: [:get, :post]
  get '/UserGuide', :to => 'time_sheets#user_guide'
  get '/ProjectsPersonnel', :to => 'projects#project_page'

  match '/auth/:provider/callback' => 'sessions#create' , via: [:get, :post]
  match "/auth/failure" => "sessions#failure", via: [:get, :post]
  get '/signin',  to: 'sessions#new'
  get '/signout', to: 'sessions#destroy'
  get '/signup', to: 'users#new'
  get '/Client', to: 'sessions#new_client'
  get '/renderRoleInfo', to: 'sessions#render_role_info'

  get '/monthlyClassifiedReport', to: 'admin#monthlyEmployeeReport'
  get '/registration', to: 'registrations#new'
  get '/view_report', to: 'time_sheets#view_report'
  get '/send_mail', to: 'time_sheets#send_mail'
  get '/activate_user', to: "time_sheets#activate_user"
  get '/time_sheet_reports', to: "time_sheets#time_sheet_reports"

    get "/project_colors", to: 'report#project_colors'
    get '/createReportPieChart', to: 'report#createReportPieChart'
    get '/createCustomReport', to: 'report#createCustomReport'
    get '/TimeSummaries', to: 'time_sheets#report'
    get '/projectReport', to: 'report#projectReport'
    get '/sendReportReminder', to: 'report#reminder'
  
    get '/send_report', to: "time_sheets#send_report"
    get '/submit_report', to: 'time_sheets#submit_report'
    get '/weeklyTimeView', to: 'time_sheets#weekly_time_view'
    get '/checkPrevWeekHours', to: 'time_sheets#check_prev_week_hours'

    get 'work_orders/index', to: 'work_orders#index'
    get '/work_order_admin', to: 'work_order_admin#index'
    get'/processReport', to: 'work_order_admin#process_report'
    get '/work_order_assignment/:id', to: 'work_order_admin#assignment'
    get '/work_order_review/:id', to: 'work_order_admin#review'
	  get '/work_order_submit', to: 'work_orders#submit'
	  get '/work_order_approve', to: 'work_order_admin#approve'
	  get '/deleteAttachment', to: 'work_orders#delete_attachment'
	  get '/buildAttachment', to: 'work_orders#build_attachment'
	  get '/WorkOrderTracking', to: 'work_order_admin#work_order_tracking'
	  get '/getAttachments', to: 'work_orders#get_attachments'
	  get '/clearAllAttachments', to: 'work_orders#clear_all_attachments'	
	  get '/checkAttachment', to: 'work_orders#check_attachment'
	  post '/dropzone', to: 'work_orders#dropzone'
	  get '/getWOData', to: 'work_order_admin#get_WO_data'
	  get '/getEmails', to: 'work_order_admin#get_emails'
	  get '/saveAWOEdits', to: 'work_order_admin#save_awo_edits'
	  get '/getOfficePercents', to: 'work_order_admin#get_office_percents'
    get "/monthly_quarterly_CSV", to: "work_order_admin#monthly_quarterly_CSV"
    get "/yearlyCSV", to: "work_order_admin#yearlyCSV"
    get "/weeklyCSV", to: "work_order_admin#weeklyCSV"
		get "/get_admin_data", to: "work_order_admin#get_admin_data"
		
		

  get "/admin", to: 'admin#index'
  get "/admin/users", to: 'admin#users'
  post "/updateUser", to: 'admin#updateUser'
  get "/reportingusers", to: "admin#assign_users"
  post "/activateProject", to: "projects#activate"
  post "/deactivateProject", to: "projects#deactivate"
  get "/archived_projects", to: "projects#archived"
  get "/archivedProjectdetails", to: "projects#archivedProjectDetails"
  get '/saveProject', to: 'projects#save_project'
  get '/archiveProject', to: 'projects#archive_project'
  get '/createProject', to: 'projects#create_project'
  get '/editUserPermissions', to: 'admin#edit_permissions'
  get '/usersTable', to: 'admin#users_table'
  get '/get_user_permissions', to: 'admin#get_user_permissions' 
  get '/delete_role', to: 'admin#delete_role'
  get '/edit_custom_role', to: 'admin#edit_custom_role'
  get '/save_new_role', to: 'admin#save_new_role'
  get '/get_custom_role_permissions', to: 'admin#get_custom_role_permissions'
  get '/load_custom_roles', to: 'admin#load_custom_roles'
  get '/get_role_hierarchy', to: 'admin#get_role_hierarchy'
  get '/load_new_role', to: 'admin#load_new_role'
  get '/load_user_info', to: 'admin#load_user_info'
  get '/disable_user', to: 'admin#disable_user'
  get '/enable_user', to: 'admin#enable_user'
  get "/delete_user", to: 'admin#delete_user'
  get '/users_table', to: 'admin#users_table'
  get'/reload_assigned_users', to: 'projects#reload_assigned_users'

  
  get "/manager", to: "manager#manager"
  post "/assignProjects", to: "manager#assignProjects"
  post "/removeProjects", to: "manager#removeProjects"
  get '/searchUsers', :to => 'manager#searchUsers'
  get '/getUsersList', :to => 'manager#getUsersList'
  
  get '/verify_report', to: 'time_sheets#verify_report'
  get '/approve_report', to: 'time_sheets#approve_report'
  get '/reject_report', to: 'time_sheets#reject_report'
  get "/manageReports", to: "admin#manageReports"
  get "/tsmanageReports", to: "admin#manageReports"
  get "/ts_manager_csvReport", to: "admin#ts_manager_csvReport"
  get '/renderUserData', to: 'admin#render_user_data'
  
  
  get '/saveModifiedHours', to: "admin#saveModifiedHours"
  post '/saveModifiedHours', to: "admin#saveModifiedHours"
  get '/newReport', to: "admin#newReportEmployee"
  get '/employeeReportUpdated', to: "admin#employeeReportUpdated"
  get '/update_user_lock', to: 'admin#update_user_lock'
  get '/update_all_locks', to: 'admin#update_all_locks'
  get '/update_project_locks', to: 'admin#update_project_locks'
  get '/update_all_project_locks', to: 'admin#update_all_project_locks'
  get '/update_prev_month_all_lock', to: 'admin#update_prev_month_all_lock'
  get '/update_prev_month_user_lock', to: 'admin#update_prev_month_user_lock'
  get '/check_TS_locks', to: 'time_sheets#check_TS_locks'
  match 'active'  => 'sessions#active',  via: :get
  match 'timeout' => 'sessions#timeout', via: :get
  
  
  
  get '/versionUpdates', to: 'versions#index'
  
  get '404', to: redirect('/')
  
    

end

app/models/project.rb
class Project < ActiveRecord::Base
attr_accessible :id, :name, :category, :acct_number, :active, :project_datas_attributes,
		:created_at, :updated_at
		
has_many :project_datas


accepts_nested_attributes_for :project_datas

def self.alphaNum
	order('acct_number ASC')
end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :require_admin, :except => :project_page
  before_filter :require_project_admin, :except => :project_page
  before_filter :require_admin_project, :except => :project_page
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  def index
    @archive_projects = ArchievedProject.all
    @user = User.find(session[:user_id])
	@projects = ProjectData.all.sort {|a,b| a.getAcctNumber <=> b.getAcctNumber}

 	#@permissions['create_projects'] || @permissions['edit_projects'] || @permissions['destroy_projects'] ||
    @permissions = session[:permissions]
    if @permissions['activate_all_projects'] || @permissions['archive_all_projects'] || @permissions['assign_users_all_projects']
		@tableViewOnly = false
	else
		@tableViewOnly = true
	end
	  	  if @user.time_sheet_manager
  	  	@time_sheet_lock = true
  	  else
  	  	@time_sheet_lock = false
  	  end
  end



  # GET /projects/1
  def show
    @project = Project.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.pdf do
        render :pdf => "2", :save_to_file => Rails.root.join('pdfs', "#{@project.name}.pdf")
      end
    end
  end

  # GET /projects/new
  def new
	@user = User.find(session[:user_id])
    @project= ProjectData.new

 	@managers = User.where(:manager => true).alpha
 	@employees = User.where(:role => 'Classified').alpha
 	@employees += User.where(:role => 'Unclassified').alpha
 #	@employees = @employees - @managers
 	@gas = User.where(:role => 'GA').alpha

	@internalAcct = {};
	InternalProjectAcctNumber.all.each do |i|
		@internalAcct[i.id] = i.acct_number
	end
  end

  # GET /projects/1/edit
  def edit
  	puts 'check edit params'
  	puts params
  	@permissions = session[:permissions]
  	@roleAllows = session[:roleAllows]
  	@wo = false
  	@project = ProjectData.find(params[:id])
  	if @project.project_type == 'wo'
  		@wo = true
  	end
 	@projectManagers = []
  	if !@project.project_managers.blank?
  		@project.project_managers.each do |pm|
  			@projectManagers << pm.user_id
  		end
 	end
 	@projectEmployees = []
 	@projectGas = []
   	if !@project.assigned_projects.blank?
  		@project.assigned_projects.each do |ap|
    		if User.exists?(:id => ap.user_id)
    			user = User.find(ap.user_id)
    			if user.role != 'GA'
			  		@projectEmployees << ap.user_id
  				else
  					@projectGas << ap.user_id
  				end
  			end
  		end
 	end


 	@managers = User.where(:manager => true).alpha
 	@employees = User.where(:role => 'Classified').alpha
 	@employees += User.where(:role => 'Unclassified').alpha
 #	@employees = @employees - @managers
 	@gas = User.where(:role => 'GA').alpha



	@user = User.find(session[:user_id])

	if @user.project_admin
		@allow = true
	else
		@allow = false
	end

	@acct_number = @project.getAcctNumber

	if !@project.project.nil?
		@internal = false
	elsif !@project.internal_project_acct_number.nil?
		@internal = true
	end

	@internalAcct = {};
	InternalProjectAcctNumber.all.each do |i|
		@internalAcct[i.id] = i.acct_number
	end


  end

   def reload_assigned_users
 	@project = ProjectData.find(params[:id])

 	@projectManagers = []
  	if !@project.project_managers.blank?
  		@project.project_managers.each do |pm|
  			@projectManagers << pm.user_id
  		end
 	end

 	@projectEmployees = []
 	@projectGas = []
   	if !@project.assigned_projects.blank?
  		@project.assigned_projects.each do |ap|
    		if User.exists?(:id => ap.user_id)
    			user = User.find(ap.user_id)
    			if user.role != 'GA'
			  		@projectEmployees << ap.user_id
  				else
  					@projectGas << ap.user_id
  				end
  			end
  		end
 	end


 	@managers = User.where(:manager => true).alpha
 	@employees = User.where(:role => 'Classified').alpha
 	@employees += User.where(:role => 'Unclassified').alpha
 #	@employees = @employees - @managers
 	@gas = User.where(:role => 'GA').alpha



	@user = User.find(session[:user_id])
	render :html => "reload_assigned_users", :layout => false
 	end



  def activate
    @project = ProjectData.find(params[:id])
    @project.active = true
    @project.save
    render :text => "success"
  end

  def deactivate
    @project = ProjectData.find(params[:id])
    @project.active = false
    @project.save
    render :text => "success"
  end

  # POST /projects
  def create
    if project_params[:name].nil?
      render :text => project_params.to_s
    end
    @project = ProjectData.new(params[:project])
    if @project.save!
      redirect_to projects_path, notice: 'Project was successfully created.'
    else
      render action: 'new'
    end
  end
# PATCH/PUT /projects/1
  def update
    puts params
    @project=ProjectData.find(params[:id])
    @project.name = params[:project][:name]
    @project.type = params[:project][:type]
    @project.project_id = params[:project][:acct_number]
	if !params[:project][:project_managers_attributes].nil?
		@project_managers = @project.project_managers
		@project_managers.each do |p|
			p.destroy
		end
		buildCount = params[:project][:project_managers_attributes].length
		count = 0
  		for i in 0..(buildCount-1)
			@project_manager = @project.project_managers.build
			@project_manager.user_id = params[:project][:project_managers_attributes][count.to_s]['user_id']
			@project_manager.save
			count += 1
		end
  	end
    if @project.save
      redirect_to projects_path, notice: 'Project was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /projects/1
  def archive_project
  	@project = ProjectData.find(params[:pid])
  	if @project.locked
   	 	@archive_project = ArchievedProject.new
    	@archive_project.name = @project.name
    	@archive_project.project_data_id = @project.id
    	if !@project.project_managers[0].nil?
      		@archive_project.user_id = @project.project_managers[0].user_id
    	end
     	if !@project.project.nil?
      		@archive_project.acct_number = @project.project.acct_number
    	end
    	@archive_project.save
    	@project.destroy
    	redirect_to projects_url, notice: 'Project was successfully archived.'
    else
    	data = {}
    	data[:fail] = true
    	data[:msg] = "Project needs to be locked by Time Sheet Manager before Archiving."
    	render :json => data
    end
  end

  def create_report
    @user = User.find(session[:user_id])
    respond_to do |format|
      format.html # show.html.erb
      format.pdf do
        render :pdf => "#{@user.name}",
        :save_to_file => Rails.root.join('pdfs', "#{@user.name}.pdf")
      end
    end
  end

  def assign
    @usr = User.find(params[:id])
    @projects = ProjectData.where(:active => true)
  end

  def archived
    @aps = ArchievedProject.all
  end

  def archivedProjectDetails
    @p = ArchievedProject.find(params[:projectId])
    @assi_prj = AssignedProject.where(:project_data_id => @p.project_data_id)
    @proj_man = ProjectManager.where(:project_data_id => @p.project_data_id)
    @tt = TimeTable.where(:project_data_id => @p.project_data_id)
    @hrs = 0
    @tt.each do |t|
      @hrs += t.hours
    end
    render :html => "archivedProjectDetails", :layout => false
  end

  def save_project
      managers = params[:managers]
      employees = params[:employees]
      gas = params[:gas]
  	  descript = params[:descript]
      project = ProjectData.find(params[:project_data_id])
      if project.project_type != 'wo'
        project.project_type = 'internal'
      end
      if !params[:name].blank?
        project.name = params[:name]
      end
    if project.valid?
          pm = project.project_managers
          if !pm.blank?
              pm.each do |pmx|
                pmx.destroy
              end
          end
          ap = project.assigned_projects
          if !ap.blank?
            ap.each do |apx|
              apx.destroy
            end
          end
          if !managers.blank?
            managers.each do |m|
              pm = project.project_managers.build
              pm.user_id = m
              pm.save
            end
          end
          puts 'check employees'
          puts employees
          if !employees.blank?
            employees.each do |e|
              ap = project.assigned_projects.build
              ap.user_id = e
              ap.save
            end
          end
          if !gas.blank?
              gas.each do |g|
                ap = project.assigned_projects.build
                ap.user_id = g
                ap.save
              end
          end
          project.description = descript
          if params[:acct] != ''
              puts 'made it here'
              if (params[:internal] == 'false') && (params[:new] == 'false')
                  pid = params[:acct]
                  project.project_id = pid
                  project.save
              elsif (params[:new] == 'true')
                  project.save
                  i = InternalProjectAcctNumber.new
                  i.project_data_id = project.id
                  i.acct_number = params[:acct]
                  i.save
              elsif (params[:internal] == 'true') && (params[:new] == 'false')
                  project.save
                  i = InternalProjectAcctNumber.find(params[:acct])
                  if i.project_data_id != project.id
                    i2 = InternalProjectAcctNumber.new
                    i2.project_data_id = project.id
                    i2.acct_number = i.acct_number
                    i2.save
                  end
              end
          else
            project.save
          end
          render :text=> 'success'
      else
          render :text => project.errors.full_messages
      end
 	 end


  def create_project
    managers = params[:managers]
    employees = params[:employees]
    gas = params[:gas]
    descript = params[:descript]
    project = ProjectData.new
    if !params[:type].blank?
      project.project_type = params[:type]
    end
	  if !params[:name].blank?

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<div class="row-fluid">
  <div class="span4 well">
<%= form_for @project, :html => {:class => "form-horizontal"} do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>
      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <fieldset>
          <legend>New Project</legend>
          <div class="control-group">  
            <%= f.label :name %>
            <div class="controls">          
              <%= f.text_field :name %>
            </div>
          </div>  
          
        
          
          
  <div class="form-actions">
    
    <%= f.submit :class => "btn btn-primary" %>
    <%= link_to 'Back to Index', projects_path, :class => "btn btn-primary" %>
  </div>
 </fieldset>
<% end %>
  </div>
</div>

app/views/projects/archived.html.erb
<div class="row">
<div class='col-xs-12'>
<table class="table table-striped table-bordered table-condensed pull-left" style="width:40%">
  <% if @aps.length > 0 %>
  <thead>
    <tr>
      <th>Name</th>      
      <th>Acct Number</th> 
      <th></th>
    </tr>
  </thead>  
  <tbody>    
    <% @aps.each do |project| %>
      <tr>
        <td><%= project.name %></td>        
        <td><%= project.acct_number %></td>                
        <td>
          <%=hidden_field_tag "projectId",project.id,:class => "projectCls" %>
          <a href="#" onclick="loadDetails($(this).parent().find('input.projectCls').val())" ><img src="/assets/more_details.ico" style="width:26px;height:26px;" /></a></td>
      </tr>
    <% end %>
  </tbody>
  <% end %>
</table>


<div id="subdetails" class="pull-left" style="margin-left:100px;width:40%;">
  
</div>
</div>
<div class="col-xs-12">
<%= link_to 'Back', '/admin/projects/', :class => "btn btn-active"%>
</div>
</div>
<script>
  function loadDetails(projectId){

    $.ajax({
                method: 'GET',
                url: '/archivedProjectdetails',
                data : "projectId="+ projectId,
                success: function(dt){
                  $("#subdetails").html(dt);
                }
            });
    
  }
  
</script>

app/views/projects/archivedProjectDetails.html.erb
<div style="width:30%">
  <fieldset>
    <legend>Details</legend>
    Manager : <% if !@proj_man.blank? %><%@proj_man.each do |p| %>
    <% user = User.where(:id => p.user_id) %>
    <%if user.blank? %>
    	<%=DisabledUser.where(:user_id => p.user_id).first.name%>
    <%else%>
    	<%=user.first.name%>
    <%end%><br />
    <%end%><% end %>
    <br/>
    Team:
    <% @assi_prj.each do |p| %>
      <b><%= User.find(p.user_id).name %></b>
      <br/>
    <% end %>
    
    <br/>
    <br/>
    Total No. Of hours: <%= @hrs %>
    </fieldset>
  
</div>

app/views/projects/index.html.erb
<table class="table table-striped table-bordered table-condensed">
  <% if @projects.length > 0 %>
    <tr>
      <th>Acct Number (Name)</th>
      <th>Project Name</th>
      <th>Type</th>
      <th>Manager(s)</th>
     <%if !@tableViewOnly%>
      <th class="btnCol"></th>
      <%end%>
		<% if @time_sheet_lock %> 
      <th class="ts_buttons"><button type="button" class="btn btn-sm btn-danger lock_all_projects" value="lock">Lock</button>
		  <button type="button" class="btn btn-sm btn-success unlock_all_projects" value="unlock">Unlock</button> 
		</th>
		<%end%>
    </tr>
  <% end %>
    <% @projects.each do |project| %>
      <tr>
      <%if !project.project.nil?%>
        <td><%= project.project.acct_number.to_s + ' (' + project.project.name.to_s + ')'%></td>
      <%elsif !project.internal_project_acct_number.nil?%>
        <td> <%=project.internal_project_acct_number.acct_number%></td>
      <%else%>
      	<td></td>
    <%end%>
        <td><%= project.name %></td>
        <td><%=project.project_type.to_s.capitalize%></td>
        <td> <% if !project.project_managers.blank? %>
        	<%project.project_managers.each do |pm|%>
        		<%if DisabledUser.where(:user_id => pm.user_id).blank? %>
        	<%= User.find(pm.user_id).last_name %><br />
        		<%end%>
        	<% end %>
        	<%end%></td>
       <%if !@tableViewOnly%> 
       <td class="btnCol">
       <% if @permissions['activate_all_projects']%>
          <% if project.active == true %>
              <input type="button" class="btn btn-warning btn-sm buttonWidth" value="Deactivate" id=<%=project.id%> onclick="deactivate(this.id)"> </input>
          <% else %>
              <input type="button" class="btn btn-warning btn-sm buttonWidth" value="Activate" id=<%=project.id%> onclick="activate(this.id)"> </input>
          <% end %>
        <%end%>
        <% if @permissions['edit_projects'] %>
        <%= link_to 'Edit', edit_project_path(project), :class => 'btn btn-success btn-sm buttonWidth' %>
        <%end%>
       <%if @permissions['archive_all_projects']%> 
	<button type="button" class=" btn btn-sm btn-danger archiveProject buttonWidth" id="<%=project.id%>">Archive</button>
	<%end%>
	</td> <%end%>
	
		<% if @time_sheet_lock %> 
			<td> <button type="button" class="btn btn-sm btn-danger lock_project" id="<%=project.id%>" <%if project.locked %> style="display:none" <%end%> value="lock">Lock</button>
				 <button type="button" class="btn btn-sm btn-success unlock_project" id="<%=project.id%>" <%if !project.locked %> style="display:none" <%end%> value="unlock">Unlock</button>
			</td>
		<%end%>
      </tr>
<%end%>


</table>

<table class="table table-striped table-bordered table-condensed">


<% if @projects.length == 0 %>
  <h3> There are no Projects to display. you can add them. </h3>
<% end %>
<br/>
<%if @permissions['create_projects']%>
<%= link_to 'New Internal Project', new_project_path, :class => "btn btn-active btn-success btn-sm"%>
<%end%>
<%= link_to 'View Archived', archived_projects_path, :class => "btn btn-active btn-primary btn-sm"%>
</div>

<style>
	a.btn:visited {
		color: white !important;
	}
	
	.buttonWidth {
		width: 85px !important;
	}
	
	.btnCol {
		text-align: center !important;
	}
	
.unlock_project, .lock_project{
	height: 30px !important;
	width: 100% !important;
	padding: 0 !important;
	margin: 0 !important;
	
}
table td {
	vertical-align: middle !important;

}


.lock_all_projects, .unlock_all_projects {

}

.ts_buttons {
	width: 129px !important;
}
</style>

<script>
  function activate(project_id){
        $.ajax({
              type: 'POST',
              url: '/activateProject',
              data : "id="+project_id,
              success: function(dt){
                //alert(dt);
                if(dt=="success"){
                  $("#"+project_id).val("Deactivate");
                  $("#"+project_id).attr("onclick","deactivate(this.id)" );               
                }
              }
          });
  }
  
  function deactivate(project_id){
        $.ajax({
              type: 'POST',
              url: '/deactivateProject',
              data : "id="+project_id,
              success: function(dt){
                if(dt=="success"){
                  $("#"+project_id).val("Activate");
                  $("#"+project_id).attr("onclick","activate(this.id)" );
                }
              }
          });  
  }

  $('.archiveProject').click(function() {
  var pid = $(this).attr('id');

  	if (confirm('Archiving the project is irreversible. This Specific Project will no longer be available to track hours. Are you sure you want to Archive this project?')){
  	  	$.ajax({
  		url: '/archiveProject',
  		data: 'pid=' + pid,
  		type: 'GET',
  		success: function(data) {
  			if (data.fail) {
  				alert(data.msg);
  			}
  			else {
  				window.location.href="/admin/projects";
  			}
  		}
  	
  	
  	});
  }
  });
  
  // Functions for Time Locking

  $('.lock_all_projects, .unlock_all_projects').click(function() {
      var lockStatus = $(this).val();

  	if (confirm('Are you sure you want to ' + lockStatus + ' all projects from having time edited?')) {
  	  	if (lockStatus == 'lock') {
  			var lockParam = 'true';
  		}
  		else {
  			var lockParam = 'false';
  		}

  		$.ajax({
  			url: '/update_all_project_locks',
  			data: {'locked': lockParam},
  			type: 'GET',
  			success: function() {
  			  	if (lockParam == 'true') {
  					$('.unlock_project').show();  					
  					$('.lock_project').hide();
  				}
  				else {
  					$('.unlock_project').hide();
  					$('.lock_project').show();
  				}    				
  				alert('All Projects have been' + lockStatus + 'ed.');
  			}
		});
  	}
  });
  
  $('.lock_project, .unlock_project').click(function() {
    var lockStatus = $(this).val();
    var project_id = $(this).attr('id');
  	if (confirm('Are you sure you want to ' + lockStatus + ' this project from having time edited?')) {
  	  	if (lockStatus == 'lock') {
  			var lockParam = 'true';
  		}
  		else {
  			var lockParam = 'false';
  		}
  		$.ajax({
  			type: 'GET',
  			url: '/update_project_locks',
  			data: {'locked': lockParam, 'project_id': project_id},
  			success: function() {
  			  	if (lockParam == 'true') {
  					$('#' + project_id + '.unlock_project').show();  					
  					$('#' + project_id + '.lock_project').hide();
  				}
  				else {
  					$('#' + project_id + '.unlock_project').hide();
  					$('#' + project_id + '.lock_project').show();
  				}  		
  				alert('This project has been ' + lockStatus + 'ed.');
  			}
  		});
  	}
  });
  
   $('.lock_all input').prop('disabled', true);


//-------------------------------
  
</script>

app/views/projects/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @project.name %>
</p>



<p>
  <strong>Category:</strong>
  <%= @project.category %>
</p>

<p>
  <strong>Account Number:</strong>
  <%= @project.acct_number %>
</p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>