config/routes.rb
MusicFeedApp::Application.routes.draw do
  get "admin/index"
  get '/admin/hoursWorked'
  root 'sessions#new'
  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  resources :work_orders
  resources :attachments
  resources :ull_team_members
  resources :password_resets

  scope "/admin" do
    resources :projects do
      collection do
        get 'assign'
      end
    end
  end
    
  scope "/admin" do
    resources :project_datas do
      collection do
        get 'assign'
      end
    end
  end
     
  resources :project_datas do
    member do
       get 'project_managers'
    end
  end

  get 'login', to: 'welcome#index'
  get '/help', to: 'welcome#help'
  get 'welcome/index', to: 'welcome#index'
  get '/load_today_data', to: 'time_sheets#loadToDay'
  post '/saveTimeSheets', to: 'time_sheets#saveTime'
  post '/saveDayTimesheets', to: 'time_sheets#saveDayTime'
  get 'welcome/weekFunc', to: 'time_sheets#weekFunc'
  get '/createPieChart', to: 'time_sheets#createPieChart'
  get '/checkPrevTimeSheets', to: 'time_sheets#checkPrevTimeSheets'
  match '/deleteDayTimesheets', :to => 'time_sheets#deleteDayTimesheets', via: [:get, :post]
  get '/UserGuide', :to => 'time_sheets#user_guide'
  get '/ProjectsPersonnel', :to => 'projects#project_page'

  match '/auth/:provider/callback' => 'sessions#create' , via: [:get, :post]
  match "/auth/failure" => "sessions#failure", via: [:get, :post]
  get '/signin',  to: 'sessions#new'
  get '/signout', to: 'sessions#destroy'
  get '/signup', to: 'users#new'
  get '/Client', to: 'sessions#new_client'
  get '/renderRoleInfo', to: 'sessions#render_role_info'

  get '/monthlyClassifiedReport', to: 'admin#monthlyEmployeeReport'
  get '/registration', to: 'registrations#new'
  get '/view_report', to: 'time_sheets#view_report'
  get '/send_mail', to: 'time_sheets#send_mail'
  get '/activate_user', to: "time_sheets#activate_user"
  get '/time_sheet_reports', to: "time_sheets#time_sheet_reports"

    get "/project_colors", to: 'report#project_colors'
    get '/createReportPieChart', to: 'report#createReportPieChart'
    get '/createCustomReport', to: 'report#createCustomReport'
    get '/TimeSummaries', to: 'time_sheets#report'
    get '/projectReport', to: 'report#projectReport'
    get '/sendReportReminder', to: 'report#reminder'
  
    get '/send_report', to: "time_sheets#send_report"
    get '/submit_report', to: 'time_sheets#submit_report'
    get '/weeklyTimeView', to: 'time_sheets#weekly_time_view'
    get '/checkPrevWeekHours', to: 'time_sheets#check_prev_week_hours'

    get 'work_orders/index', to: 'work_orders#index'
    get '/work_order_admin', to: 'work_order_admin#index'
    get'/processReport', to: 'work_order_admin#process_report'
    get '/work_order_assignment/:id', to: 'work_order_admin#assignment'
    get '/work_order_review/:id', to: 'work_order_admin#review'
	  get '/work_order_submit', to: 'work_orders#submit'
	  get '/work_order_approve', to: 'work_order_admin#approve'
	  get '/deleteAttachment', to: 'work_orders#delete_attachment'
	  get '/buildAttachment', to: 'work_orders#build_attachment'
	  get '/WorkOrderTracking', to: 'work_order_admin#work_order_tracking'
	  get '/getAttachments', to: 'work_orders#get_attachments'
	  get '/clearAllAttachments', to: 'work_orders#clear_all_attachments'	
	  get '/checkAttachment', to: 'work_orders#check_attachment'
	  post '/dropzone', to: 'work_orders#dropzone'
	  get '/getWOData', to: 'work_order_admin#get_WO_data'
	  get '/getEmails', to: 'work_order_admin#get_emails'
	  get '/saveAWOEdits', to: 'work_order_admin#save_awo_edits'
	  get '/getOfficePercents', to: 'work_order_admin#get_office_percents'
    get "/monthly_quarterly_CSV", to: "work_order_admin#monthly_quarterly_CSV"
    get "/yearlyCSV", to: "work_order_admin#yearlyCSV"
    get "/weeklyCSV", to: "work_order_admin#weeklyCSV"
		get "/get_admin_data", to: "work_order_admin#get_admin_data"
		
		

  get "/admin", to: 'admin#index'
  get "/admin/users", to: 'admin#users'
  post "/updateUser", to: 'admin#updateUser'
  get "/reportingusers", to: "admin#assign_users"
  post "/activateProject", to: "projects#activate"
  post "/deactivateProject", to: "projects#deactivate"
  get "/archived_projects", to: "projects#archived"
  get "/archivedProjectdetails", to: "projects#archivedProjectDetails"
  get '/saveProject', to: 'projects#save_project'
  get '/archiveProject', to: 'projects#archive_project'
  get '/createProject', to: 'projects#create_project'
  get '/editUserPermissions', to: 'admin#edit_permissions'
  get '/usersTable', to: 'admin#users_table'
  get '/get_user_permissions', to: 'admin#get_user_permissions' 
  get '/delete_role', to: 'admin#delete_role'
  get '/edit_custom_role', to: 'admin#edit_custom_role'
  get '/save_new_role', to: 'admin#save_new_role'
  get '/get_custom_role_permissions', to: 'admin#get_custom_role_permissions'
  get '/load_custom_roles', to: 'admin#load_custom_roles'
  get '/get_role_hierarchy', to: 'admin#get_role_hierarchy'
  get '/load_new_role', to: 'admin#load_new_role'
  get '/load_user_info', to: 'admin#load_user_info'
  get '/disable_user', to: 'admin#disable_user'
  get '/enable_user', to: 'admin#enable_user'
  get "/delete_user", to: 'admin#delete_user'
  get '/users_table', to: 'admin#users_table'
  get'/reload_assigned_users', to: 'projects#reload_assigned_users'

  
  get "/manager", to: "manager#manager"
  post "/assignProjects", to: "manager#assignProjects"
  post "/removeProjects", to: "manager#removeProjects"
  get '/searchUsers', :to => 'manager#searchUsers'
  get '/getUsersList', :to => 'manager#getUsersList'
  
  get '/verify_report', to: 'time_sheets#verify_report'
  get '/approve_report', to: 'time_sheets#approve_report'
  get '/reject_report', to: 'time_sheets#reject_report'
  get "/manageReports", to: "admin#manageReports"
  get "/tsmanageReports", to: "admin#manageReports"
  get "/ts_manager_csvReport", to: "admin#ts_manager_csvReport"
  get '/renderUserData', to: 'admin#render_user_data'
  
  
  get '/saveModifiedHours', to: "admin#saveModifiedHours"
  post '/saveModifiedHours', to: "admin#saveModifiedHours"
  get '/newReport', to: "admin#newReportEmployee"
  get '/employeeReportUpdated', to: "admin#employeeReportUpdated"
  get '/update_user_lock', to: 'admin#update_user_lock'
  get '/update_all_locks', to: 'admin#update_all_locks'
  get '/update_project_locks', to: 'admin#update_project_locks'
  get '/update_all_project_locks', to: 'admin#update_all_project_locks'
  get '/update_prev_month_all_lock', to: 'admin#update_prev_month_all_lock'
  get '/update_prev_month_user_lock', to: 'admin#update_prev_month_user_lock'
  get '/check_TS_locks', to: 'time_sheets#check_TS_locks'
  match 'active'  => 'sessions#active',  via: :get
  match 'timeout' => 'sessions#timeout', via: :get
  
  
  
  get '/versionUpdates', to: 'versions#index'
  
  get '404', to: redirect('/')
  
    

end

app/models/work_order.rb
class WorkOrder < ActiveRecord::Base
has_many :work_order_clients
has_many :users, :through => :work_order_clients
has_many :attachments
has_many :work_order_feedbacks, :dependent => :destroy
has_one :actual_work_order
has_one :project_data, :through => :actual_work_order
has_many :ull_team_members, :dependent => :destroy

accepts_nested_attributes_for :attachments
accepts_nested_attributes_for :ull_team_members, allow_destroy: true

attr_accessible :work_order_number, :project_name, :work_order_type, :UNO_project_manager, 
				:business_owner, :program_office, :due_date, :ULL_start_date, :development_end_date, 
      			:close_date, :estimated_hours, :ULL_contact, :summary, :deliverables, :comments, 
      			:attachments_attributes, :ull_team_members_attributes, :id

def self.alpha
	order(:work_order_number, :project_name)
end

def self.sort_by_type
	order(:work_order_type)
end

################################## JOIN USERS TABLE TO IGNORE DISABLED
def self.submitted 
	where(:submitted=>true, :approved=>false).joins(:users)
end

def self.approved
	where(:submitted=> true, :approved => true).joins(:users)
end

def self.resubmit
	where(:submitted=>false, :approved=>nil).joins(:users)
end

def self.rejected
	where(:submitted=>nil, :approved=>false).joins(:users)
end


def self.cancelled
	where(:submitted=>nil, :approved=>nil).joins(:users)
end

def self.saved
	where(:submitted=>false, :approved=>false).joins(:users)
end

####### ALL USERS CONSIDERED
def self.submitted_all_users 
	where(:submitted=>true, :approved=>false)
end

def self.approved_all_users
	where(:submitted=> true, :approved => true)
end

def self.resubmit_all_users
	where(:submitted=>false, :approved=>nil)
end

def self.rejected_all_users
	where(:submitted=>nil, :approved=>false)
end


def self.cancelled_all_users
	where(:submitted=>nil, :approved=>nil)
end

def self.saved_all_users
	where(:submitted=>false, :approved=>false)
end
############

def self.is_type_project
	where(:work_order_type => 'project')
end

def self.is_type_support
	where(:work_order_type => 'support')
end

def self.is_type_maintenance
	where(:work_order_type => 'maintenance')
end

def self.is_type_admin
	where(:work_order_type => 'admin')
end




def self.is_medicaid
	where(:program_office => 'medicaid')
end

def self.is_oph
	where(:program_office => 'oph')
end

def self.is_obh
	where(:program_office => 'obh')
end

def self.is_oaas
	where(:program_office => 'oaas')
end

def self.is_ocdd
	where(:program_office => 'ocdd')
end

def self.is_os
	where(:program_office => 'os')
end

end

app/controllers/work_orders_controller.rb
class WorkOrdersController < ApplicationController
  before_filter :require_activation, :except => ["activate_user","test_mail"]
  before_filter :require_client
  before_filter :set_WO_groups, :only => [:index, :show, :edit, :new]


  def set_WO_groups
    @client = User.find(session[:user_id])
    @work_orders = @client.work_orders
    @work_order_admin = User.where(:work_order_admin => true)
    if @work_order_admin.count > 1 
      @multiple_admin = true
    else
      @multiple_admin = false
    end
  	@saved_work_orders = @work_orders.saved
    @submitted_work_orders = @work_orders.submitted
    @approved_work_orders = @work_orders.approved
    @resubmit_work_orders = @work_orders.resubmit
    @rejected_work_orders = @work_orders.rejected
    @cancelled_work_orders = @work_orders.cancelled   
  end
  
  # GET /work_orders
  def index
  	Attachment.all.each do |a|
  		if a.work_order_id.nil?
  			a.destroy
  		end
  	end
    @work_order_admin = User.where(:work_order_admin => true)
    if @work_order_admin.count > 1
    	@multiple_admin = true
    else
    	@multiple_admin = false
		@work_order_admin = @work_order_admin[0]
	end
    
     
  end

  # GET /work_orders/1
  def show
  	puts 'check out show'
  	puts params
  	@work_order = WorkOrder.find(params[:id])
	@feedback = WorkOrderFeedback.where(:client_id => session[:user_id], :work_order_id => @work_order.id)
  end

  # GET /work_orders/new
  def new
  	puts 'Made it here'
    @work_order = WorkOrder.new
    @work_order.ull_team_members.build
    @work_order.attachments.build
    @show = true
    


  end

  # GET /work_orders/1/edit
  def edit
  	@work_order = WorkOrder.find(params[:id])
  	if @work_order.attachments.count == 0
  		@work_order.attachments.build
  	end
  	if @work_order.ull_team_members.count == 0
  		@work_order.ull_team_members.build
  	end
  	if @work_order.approved || @work_order.submitted
  		@show = false
  	else
  		@show = true
  	end
  end

  


  # POST /work_orders
  def create
  	 puts 'check here'
  	puts params
    @work_order = WorkOrder.new(params[:work_order])
    @work_order_client = WorkOrderClient.new
    @work_order_client.user_id = session[:user_id]
    if @work_order.save
    	@work_order_client.work_order_id = @work_order.id
    	@attachments = Attachment.where(:work_order_id => nil)
    	@attachments.each do |a|
    		a.work_order_id = @work_order.id
    		a.save
    	end
    	
    	
    	if @work_order_client.save
    		redirect_to @work_order, notice: 'Work order was successfully created.'
    	else
    		render action: 'new'
    	end
    else
      render action: 'new'
    end
  end
  





  # PATCH/PUT /work_orders/1
  def update
  	puts params[:work_order]
  	@work_order = WorkOrder.find(params[:id])
  	ull_tm_atts = params[:work_order][:ull_team_members_attributes]
  	ull_tm_atts.each do |key, value|
  		if value.length < 2 && !value['id'].blank?
  		  	attr = UllTeamMember.find(value['id'].to_i).destroy
  			params[:work_order][:ull_team_members_attributes] = params[:work_order][:ull_team_members_attributes].except!(key)
  		end
  	end
  	puts 'new params'
  	puts params
    if @work_order.update(params[:work_order])
      redirect_to @work_order, notice: 'Work order was successfully updated.'
    else
      render action: 'edit'
    end
  end



  def submit
  	data = {}
  	@work_order = WorkOrder.find(params[:id])
  	@work_order.submitted = true
  	@work_order.approved = false
  	if @work_order.save
  		data[:success]= true
  		admins = User.where(:work_order_admin => true)
  		admins.each do |a|
	   		WelcomeMailer.WO_request_alert(a, @work_order).deliver
		end
  		render :json => data.to_json

  	else
  		data[:success] = false
  		render :json => data.to_json
  	end  	
  end
  
  # DELETE /work_orders/1
  def destroy
  	puts params
  	puts 'check destroy'
  	work_order = WorkOrder.find(params[:id])
  	attachments = work_order.attachments
  	attachments.each do |a|
  		a.destroy
  	end
  	wo_clients = work_order.work_order_clients
  	wo_clients.each do |w|
  		w.destroy
  	end
    redirect_to work_orders_url, notice: 'Work order was successfully destroyed.'
  end
  
  def get_attachments
  	puts params
  	data= {}
  	if params[:work_order_id] != ''
  		@work_order = WorkOrder.find(params[:work_order_id])
  		@attachments = @work_order.attachments
  	else
  		@attachments = []
  	end
	render :json => @attachments.to_json
  end

	def check_attachment
		data = {}
  	if params[:work_order_id] != ''
		@work_order = WorkOrder.find(params[:work_order_id])
		@attachments = @work_order.attachments
		file_name = params[:file_name]
		new_file_name = file_name.tr(" ", "_")
		data[:already_exists] = false
		@attachments.each do |a|
			if File.basename(a.attachment.to_s) == new_file_name
				data[:already_exists] = true
				data[:url] = a.attachment_url
				data[:aid] = a.id
			end
		end
				render :json => data.to_json

	else
		render :json => data.to_json
	end
	end

	def delete_attachment
		@attachment = Attachment.find(params[:aid])
		data = {}
		if @attachment.destroy
			data[:success] = true
		end
		
		render :json => data.to_json
		
	end


  
  def work_order_tracking
  	@actualWorkOrders = []
  	@client = User.find(session[:user_id])
  	@work_orders = @client.work_orders.approved
  	@work_orders.each do |w|
  		 @actualWorkOrders << w.actual_work_order
  	end
  end
  
  
  
  def dropzone
    attachments_uploaded = []
  	length = params[:attachment].length
		response = {}
		success = false
  	for i in 0..(length-1)
  		if !params[:work_order_id].blank?
  			@work_order = WorkOrder.find(params[:work_order_id])
  	 		@attachment = @work_order.attachments.build
  	 		@attachment.attachment = params[:attachment][i.to_s]
  	 		if @attachment.save
  	 			success = true
				else
					success = false
				end
			else
  	 		@attachment = Attachment.new
  	 		@attachment.attachment = params[:attachment][i.to_s]
  	 		if @attachment.save
  	 			success = true
				else
					success = false
				end
			end
		end
		response[:success] = success
		render :json => response.to_json
 end

	

end

app/helpers/work_orders_helper.rb
module WorkOrdersHelper
end

app/views/work_orders/edit.html.erb
<%= render 'form' %>

<%= link_to 'Show', @work_order %> |
<%= link_to 'Back', work_orders_path %>

app/views/work_orders/index.html.erb
<% if session[:user_id] %>  
  <%@user = User.find(session[:user_id]) %>

<div class="row">
<div class="col-xs-12 topRow"> <div class="pull-left"> <a class="btn btn-sm btn-success newWorkOrder" href='/work_orders/new'>New Work Order</a></div>
</div>

<div class="col-xs-6">
<% if @saved_work_orders.count > 0 %> 
  <fieldset class="scheduler-border">
    <legend class="scheduler-border" style="color:green">Saved</legend>
<table class="table table-condensed table-bordered">
  	<thead>
  		<th>Work Order Number</th>
  		<th> Project Name</th>
  		<th></th>
  	</thead>
  <tbody>
   <% @saved_work_orders.each do |w| %>
      <tr>
      	<td> <%=w.work_order_number%> </td>
      	<td> <%=w.project_name%> </td>
        <td><%= link_to 'View', w, class: "btn btn-sm btn-default" %>
        <%= link_to 'Edit', edit_work_order_path(w), class: "btn btn-sm btn-default" %>
        <%= link_to 'Delete', w, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-sm btn-danger" %></td>
      </tr>

    <% end %>
  </tbody>
</table>
    </fieldset>
    <%end%>


<% if @resubmit_work_orders.count > 0 %>     	
  <fieldset class="scheduler-border">
    <legend class="scheduler-border">On Hold</legend>
<table class="table table-condensed table-bordered">
  	<thead>
  		<th>Work Order Number</th>
  		<th> Project Name</th>
        <th>Latest Feedback</th>
  		<th></th>

  	</thead>
  <tbody>

    <% @resubmit_work_orders.each do |w| %>
      <tr>
      	<td> <%=w.work_order_number%> </td>
      	<td> <%=w.project_name%> </td>
        <%if !w.work_order_feedbacks[-1].nil?%>
        <td><%=w.work_order_feedbacks[-1].feedback%></td>
        <% else %>
        <td></td>
        <%end%>
        <td><%= link_to 'View', w, class: "btn btn-sm btn-default" %><%= link_to 'Edit', edit_work_order_path(w), class: "btn btn-sm btn-default" %></td>
      </tr>

    <% end %>
  </tbody>
</table>
  </fieldset>
    <%end %>

<% if @rejected_work_orders.count > 0 %>
  <fieldset class="scheduler-border">
    <legend class="scheduler-border" style="color:red">Rejected</legend>
<table class="table table-condensed table-bordered">
  	<thead>
  		<th>Work Order Number</th>
  		<th> Project Name</th>
  		<th>Latest Feedback</th>
  		<th></th>

  	</thead>
  <tbody>

    <% @rejected_work_orders.each do |w| %>
      <tr>
      	<td> <%=w.work_order_number%> </td>
      	<td> <%=w.project_name%> </td>
        <%if !w.work_order_feedbacks[-1].nil?%>
        <td><%=w.work_order_feedbacks[-1].feedback%></td>
        <% else %>
        <td></td>
        <%end%>
        <td><%= link_to 'View', w, class: "btn btn-sm btn-default" %><%= link_to 'Delete', w, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-sm btn-danger" %></td>
        

      </tr>

    <% end %>
  </tbody>
</table>
    </fieldset>
    <%end %>

<% if @cancelled_work_orders.count > 0 %>     	

  <fieldset class="scheduler-border">
    <legend class="scheduler-border">Cancelled</legend>
<table class="table table-condensed table-bordered">
  	<thead>
  		<th>Work Order Number</th>
  		<th> Project Name</th>
  		<th></th>
  		<th></th>
  	</thead>
  <tbody>
    <% @cancelled_work_orders.each do |w| %>
      <tr>
      	<td> <%=w.work_order_number%> </td>
      	<td> <%=w.project_name%> </td>
      	<td></td>
        <td><%= link_to 'View', w, class: "btn btn-sm btn-default" %><%= link_to 'Delete', w, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-sm btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
    </fieldset>
  <%end %>

</div>
<div class="col-xs-6">

<% if @submitted_work_orders.count > 0 %>    
  <fieldset class="scheduler-border">
    <legend class="scheduler-border">Submitted</legend>
<table class="table table-condensed table-bordered ">
  	<thead>
  		<th>Work Order Number</th>
  		<th> Project Name</th>
  		<th></th>
  	</thead>
  <tbody>

    <% @submitted_work_orders.each do |w| %>
      <tr>
      	<td> <%=w.work_order_number%> </td>
      	<td> <%=w.project_name%> </td>
        <td><%= link_to 'View', w, class: "btn btn-sm btn-default" %><%= link_to 'Edit', edit_work_order_path(w), class: "btn btn-sm btn-default" %></td>
      </tr>

    <% end %>
  </tbody>
</table>
  </fieldset>
    <%end %>

<% if @approved_work_orders.count > 0 %>
  <fieldset class="scheduler-border">
    <legend class="scheduler-border" style="color:green">Approved</legend>
<table class="table table-condensed table-bordered">


  	<thead>
  		<th>Work Order Number</th>
  		<th> Project Name</th>
  		<th>Latest Feedback</th>
  		<th></th>
  	</thead>
  <tbody>

    <% @approved_work_orders.each do |w| %>
      <tr>
      	<td> <%=w.work_order_number%> </td>
      	<td> <%=w.project_name%> </td>
        <%if !w.work_order_feedbacks[-1].nil?%>
        <td><%=w.work_order_feedbacks[-1].feedback%></td>
        <% else %>
        <td></td>
        <%end%>
     	<td><%= link_to 'View', w, class: "btn btn-sm btn-default" %><%= link_to 'Edit', edit_work_order_path(w), class: "btn btn-sm btn-default" %></td>
      </tr>

    <% end %>
  </tbody>
</table>
  </fieldset>
    <%end %>
</div>

</div>

<div class="pull-down">
<div class="col-xs-12"> 
	<div class="pull-right">
		<span class="label label-default">CBIT Work Order Contact</span> 
		<%if @multiple_admin%> 
			<%@work_order_admin.each do |w|%>
				<%=w.first_name%> <%=w.last_name%>:  <a href='mailto:<%=w.email%>' style="color:blue;"><u><%=w.email%></u></a>
			<%end%>
		<%else%> 
    <%if !@work_order_admin.nil?%>
			<%w = @work_order_admin%> 
			<%=w.first_name%> <%=w.last_name%>:  <a href='mailto:<%=w.email%>' style="color:blue;"><u><%=w.email%></u></a>
		<%end%>
    <%end%>

</div>
</div>
</div>


<style>




.btn:not(.btn-default) {
	color: white !important;

}

  fieldset.scheduler-border {
    border: 1px groove #ddd !important;
    border-radius: 8px !important;
    padding: 0 1.4em 1.4em 1.4em !important;
    margin: 0 0 1.5em 0 !important;
    -webkit-box-shadow:  0px 0px 0px 0px #000;
            box-shadow:  0px 0px 0px 0px #000;
  }

  legend.scheduler-border {
      font-size: .9em !important;
	  border-bottom: 0px !important;
  }  
  
  legend.scheduler-border {
    width:inherit; /* Or auto */
    padding:0px; /* To give a bit of padding on the left and right */
    /*border-bottom:none; */
}

table {
	margin-bottom: 0px !important;
}

.topRow {
	margin-bottom: 5px !important;
}
</style>

<script>
$(document).ready( function() {
    $(".work-order-home-client").addClass("active");  
  	$('.pull-down').each(function() {
    	$(this).css('margin-top', $(this).parent().height()-($(this).height() + 20));

	});
	overrideAlertBanner('', '');
});

</script>

<%end%>

app/views/work_orders/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', work_orders_path%>

app/views/work_orders/work_order_admin.html.erb
<%w = @work_order%>
<p id="notice"><%= notice %></div></p>
<p><div class="title">Work Order Number</div><%=w.work_order_number%></p>
<p><div class="title">Project Name</div><%=w.project_name%></p>
<p><div class="title">Type</div><%=w.work_order_type%></p>
<p><div class="title">UNO Project Manager</div><%=w.UNO_project_manager%></p>
<p><div class="title">Business Owner</div><%=w.business_owner%></p>
<p><div class="title">Program Office</div><%=w.program_office%></p>
<p><div class="title">Due Date</div><%=w.due_date%></p>
<p><div class="title">ULL Start Date</div><%=w.ULL_start_date%></p>
<p><div class="title">Development End Date</div><%=w.development_end_date%></p>
<p><div class="title">Close Date</div><%=w.close_date%></p>
<p><div class="title">Estimated Hours</div><%=w.estimated_hours%></p>
<p><div class="title">ULL Contact</div><%=w.ULL_contact%></p>
<p><div class="title">Summary</div><%=w.summary%></p>
<p><div class="title">Deliverables</div><%=w.deliverables%></p>
<p><div class="title">Comments</div><%=w.comments%></p>
<p><div class="title">Attachments</div><%=w.attachments%></p>

<%= link_to 'Edit', edit_work_order_path(@work_order) %> |
<%= link_to 'Back', work_orders_path %>

app/views/work_orders/work_order_tracking.html.erb
<%@actualWorkOrders.each do |w| %>
	Tracking Data for <%=w.work_order.project_name%> <br />
	Work Order Number: <%= w.work_order.work_order_number%><br />
	Project Description: <%= w.project_description%><br />
	<%if !w.project_manager_id.blank?%>
		Project Manager: 
		<%projectManager = User.find(w.project_manager_id)%>
		<%=projectManager.last_name + ', ' + projectManager.last_name %><br />
	<%end%>
	Start Date: <%=w.start_date%><br />
	End Date: <%=w.end_date%><br />
	Work Order Status: <%=w.work_order_status%><br />
	Work Order Progress Status: <%=w.work_progress_status%><br />
	Total Hours Worked: <%=w.work_order.project.time_tables.getTotal%>
<%end%>
	
	